# Generated by Django 5.0 on 2026-02-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_linkedin_fields_and_entries'),
        ('profiles', '0002_repair_profile_schema'),
    ]

    operations = [
    ]
