# Generated by Django 5.0 on 2026-02-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_merge_20260210_2051'),
        ('profiles', '0004_repair_profile_missing_columns'),
    ]

    operations = [
    ]
