# Generated by Django 5.2.11 on 2026-02-16 04:41

from django.db import migrations, models


def set_recruiter_profile_roles(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    Recruiter = apps.get_model('accounts', 'Recruiter')
    recruiter_user_ids = Recruiter.objects.values_list('user_id', flat=True)
    Profile.objects.filter(user_id__in=recruiter_user_ids).update(role='recruiter')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0005_merge_20260212_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter')], db_index=True, default='job_seeker', max_length=20),
        ),
        migrations.RunPython(set_recruiter_profile_roles, migrations.RunPython.noop),
    ]
