# Generated by Django 6.0.2 on 2026-02-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_merge_20260212_2031'),
        ('profiles', '0006_profile_role'),
    ]

    operations = [
    ]
