# Generated by Django 5.0 on 2026-02-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_merge_0005_merge_20260212_2031_0006_profile_role'),
        ('profiles', '0008_profile_field_embeddings'),
    ]

    operations = [
    ]
