# Generated by Django 5.0 on 2026-02-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_merge_20260228_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('open', 'Open to recruiters'), ('hidden', 'Hidden')], default='open', max_length=10),
        ),
    ]
