# Generated by Django 5.2.10 on 2026-02-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_date']},
        ),
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-Site'), ('hybrid', 'Hybrid')], default='onsite', max_length=10),
        ),
    ]
