# Generated by Django 5.0 on 2026-02-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_field_embeddings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
