# Generated by Django 5.0 on 2026-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_logos/'),
        ),
    ]
